### ISSUE TITLE
Support Path Item references

### ISSUE THREAD

**Issue by petershaw** [apple/swift-openapi-generator#128]
A file that works in openapi generator does not work in openapi-generator. The section that causes the error is: 
```yaml
paths:
  /documents:
    $ref: './paths/documents.yaml#/documents'
  /documents/{document-ident}:
    $ref: './paths/documents.yaml#/documents-detail'
```
in the root file. 

Error: 
```
error: Inconsistency encountered when parsing `Vendor Extension` under the `/documents` path: Found at least one vendor extension property that does not begin with the required 'x-' prefix. Invalid properties: [ $ref ].
```

We always have our paths in separate files for various reasons. This never was a problem before so I think swift-openapi-generator should implement it. ;)

**Comment by czechboy0** [comment]
cc @mattpolzin as I suspect this support would first need to be added in OpenAPIKit

**Comment by czechboy0** [comment]
This is specifically about Path Item references, not external references, which we're discussing separately in #.

**Comment by mattpolzin** [comment]
Tracking this as a bug here: https://github.com/mattpolzin/OpenAPIKit/issues/280

**Comment by mattpolzin** [comment]
This bug should be fixed with the new alpha release. Note the breaking changes described on the Release page: https://github.com/mattpolzin/OpenAPIKit/releases/tag/3.0.0-alpha.9

**Comment by czechboy0** [comment]
Amazing, thank you @mattpolzin. I marked this issue as unblocked now, for anyone who wants to pick it up.

**Comment by czechboy0** [comment]
Fixed in #147.

**Comment by czechboy0** [comment]
To clarify, in 3.0 there isn't much we can do, as we don't yet support external references, which is the only way to have a Path Item reference.

In 3.1, there is work to do, but we don't support that yet. Maybe that's what we should use this issue to track, let me reopen and retitle.

**Comment by dannflor** [comment]
Would like to see this happen soon. Now that I'm trying to generate from multiple documents to work around #551 it's non-negotiable that I need to be able to share schemas between the documents and external `$ref` is the only way to do that without pre-build tooling and a lot of pain.

**Comment by czechboy0** [comment]
Hi @dannflor, note that this issue is only about Path references. If you're looking for an issue tracking splitting your document into multiple documents that reference each other, that's https://github.com/apple/swift-openapi-generator/issues/25.

**Comment by simonjbeaumont** [comment]
> it's non-negotiable

All our triaged issues are things that we agree should be done; it's just a matter of resource. Sadly, we don't have infinite resource, which makes everything negotiable 😊. 

Is this something you'd be willing to contribute?

**Comment by heroes3lover** [comment]
anyone knows which tool can preview the spec with ref path correctly? I tried a few like editor.swagger and openapi swagger editor in vs extension, both are complaining about the ref info in the main json file. thanks.

**Comment by 2martens** [comment]
It works for the Swagger UI within IntelliJ. But I use the `$ref` solely to reference entries under the components object. That way a common schema can be referenced from different API files.

For example, an `ErrorResponse` references the common error schema:

```yaml
    ErrorResponse:
      description: Represents an error response
      content:
        application/json:
          schema:
            $ref: '../common/errors.yaml#/components/schemas/Error'
```
