### ISSUE TITLE
Is OAS 3 Bearer Authentication supported?

### ISSUE THREAD

**Issue by sureshjoshi** [apple/swift-openapi-generator#129]
Hi, just discovered this library earlier today and it looks awesome!

Question though: I tried creating an `openapi.yml` ending with this information (as per https://swagger.io/docs/specification/authentication/bearer-authentication/).

```
# 1) Define the security scheme type (HTTP bearer)
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
# 2) Apply the security globally to all operations
security:
  - bearerAuth: []         # use the same name as above
```

The generated code has no mention to `Authorization: Bearer <token>` or anything that would appear to give me a location to apply my token.

I'm guessing I could do it manually using middleware, but just wondering what the level of support is at the moment.

Thanks!

**Comment by sureshjoshi** [comment]
Nevermind, I didn't even see this file:
https://github.com/apple/swift-openapi-generator/blob/main/Sources/swift-openapi-generator/Documentation.docc/Articles/Supported-OpenAPI-features.md

🤦🏽

**Comment by sureshjoshi** [comment]
And for posterity for anyone else looking for this, the ClientMiddleware docs cover this exact workflow:

```
/// For example, to implement a middleware that injects the "Authorization"
/// header to every outgoing request, define a new struct that conforms to
/// the `ClientMiddleware` protocol:
///
///     /// Injects an authorization header to every request.
///     struct AuthenticationMiddleware: ClientMiddleware {
///
///         /// The token value.
///         var bearerToken: String
///
///         func intercept(
///             _ request: Request,
///             baseURL: URL,
///             operationID: String,
///             next: (Request, URL) async throws -> Response
///         ) async throws -> Response {
///             var request = request
///             request.headerFields.append(.init(
///                 name: "Authorization", value: "Bearer \(bearerToken)"
///             ))
///             return try await next(request, baseURL)
///         }
///     }
```

**Comment by czechboy0** [comment]
Glad to see the docs were useful 🙂 Indeed, this is a missing feature tracked by #37. A workaround is to create a simple Middleware, like we document on the type.

**Comment by Jonovono** [comment]
@sureshjoshi how do you then extract that on the server side and verify the jwt token? And how do you define the openapi..yaml? I got the middleware on the client working I think, but since the generated client doesn't build it not sure how to access it

**Comment by sureshjoshi** [comment]
Hey, the server for this project is in .NET, so I'm not sure how much help the code would be on that side. I've never used the Swift OpenAPI server components. 

The OpenAPI uses the bearerAuth "stuff" (https://swagger.io/docs/specification/authentication/bearer-authentication/):

```
  securitySchemes:
    bearerAuth:
      type: http
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization:
        Bearer {token}"'
      scheme: bearer
      bearerFormat: JWT
security:
- bearerAuth: []
```
