### ISSUE TITLE
Including the '\r\n' newline in a description results in non-compiling code

### ISSUE THREAD

**Issue by MacFriis** [apple/swift-openapi-generator#143]
using asp.net to write a web api, with Swashbuckle to document the api. the swagger.yaml files puts in \r\n if the documentation is on multiple lines 
C# - .net 
```
/// <summary>
/// get all words within the category and language
/// if the user is registered, this list will include words from other users
/// </summary>
/// <param name="category"></param>
/// <param name="language"></param>
/// <returns></returns>
[HttpGet, AllowAnonymous]
public async Task<ActionResult<List<Word>>> GetWords(
   [FromQuery] string category = "general",
   [FromHeader] string language = "en"
   ) ...
```
the resulting yaml file will have this 

```
 get:
      tags:
        - Words
      summary: "get all words within the category and language\r\nif the user is registered, this list will include words from other users"
      parameters:
        - name: category
          in: query
          description: ''
          style: form
          schema:
            type: string
            default: general
        - name: language
         ...
```
This result in a compile error:
```
1157: }
1158: }
1159: }
---
514:153: expected ')' to end parameter clause
===
514:153: expected ')' to end parameter clause
Command PhaseScriptExecution failed with a nonzero exit code
```
