### ISSUE TITLE
Generating client for GitHub API fails

### ISSUE THREAD

**Issue by heikowitte** [apple/swift-openapi-generator#186]
Compiling a client for the GitHub API using the dereferenced version of the [API spec](https://github.com/github/rest-api-description/blob/main/descriptions/api.github.com/dereferenced/api.github.com.deref.yaml) fails with the following error:

```
Found neither a $ref nor a Example in .content['application/json'].examples.example-3 for the request body of the **PATCH** endpoint under `/repos/{owner}/{repo}/import`. 
```

This is what the relevant section from the spec looks like:

```yaml
examples:
              example-1:
                summary: Update authentication for an import
                value:
                  vcs_username: octocat
                  vcs_password: secret
              example-2:
                summary: Updating the project choice
                value:
                  vcs: tfvc
                  tfvc_project: project1
                  human_name: project1 (tfs)
              example-3:
                summary: Restarting an import
```

Removing `example-3` from the spec (for testing) leads to the compilation failing without any specific error descriptions:

```
Command PhaseScriptExecution failed with a nonzero exit code
```
