### ISSUE TITLE
Support integer-based enums

### ISSUE THREAD

**Issue by bartoszirzyk** [apple/swift-openapi-generator#241]
Hi, I've got an enum defined in yaml file:
```
            startMinute:
              type: object
              required:
              - value
              - type
              - unit
              properties:
                value:
                  type: integer
                  enum:
                  - 0
                  - 10
                  - 20
                  - 30
                  - 40
                  - 50
                  example: 10
                type:
                  type: string
                  example: number
                unit:
                  type: string
                  example: minute
```

this is parsed to:
```
public var value: Swift.Int
public var _type: Swift.String
public var unit: Swift.String
```

I expect that if it is an enum, the `value` should be an enum type with Int as it's rawValue
