### ISSUE TITLE
Date nested in allOf/oneOf/anyOf doesn't use the configured decoding strategy

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#263]
This was discovered in the k8s API, which (simplified) uses this pattern:

```yaml
Foo:
  allOf:
    type: string
    format: date-time
```

When decoding the generated struct with the single value property in it of type Date, the Date decoding doesn't get caught by the decoding strategy on the JSONDecoder, instead it goes directly to `Date.init(from:)`, because of how we generate the code.
