### ISSUE TITLE
Consider flattening allOf + 1 subschema as a way to add descriptions to properties

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#31]
OpenAPI 3.0.x doesn't support adding descriptions to object properties, only to schemas.

That's not a problem when the schema is an inline one, as the description of the inline schema simply becomes the description of the property (works today).

However, when the property references a schema in `#/components/schemas/...`, there's no room to put a description on the property.

For example, consider:

```yaml
components:
  schemas:
    Route:
      type: object
      properties:
        from:
          $ref: '#components/schemas/Location'
        to:
          $ref: '#components/schemas/Location'
      required:
        - from
        - to
```

Above, one might reasonably want to document the `from` and `to` properties differently, but can't in OpenAPI 3.0 (however, it is possible to add descriptions to `$ref` schemas in OpenAPI 3.1).

A commonly used workaround, even [recommended](https://github.com/OAI/OpenAPI-Specification/issues/2033#issuecomment-543973334) by the JSON schema contributors, is to wrap the reference in an `allOf` inline schema, and add the property there, making it:

```yaml
components:
  schemas:
    Route:
      type: object
      properties:
        from:
          description: The location from which the traveler departs.
          allOf:
            - $ref: '#components/schemas/Location'
        to:
          description: The location to which the traveler arrives.
          allOf:
            - $ref: '#components/schemas/Location'
      required:
        - from
        - to
```

Today, the generator produces a struct for the `allOf`, meaning that all access to the nested schema is with an extra property access.

Since this is an officially recommended workaround for a design issue in OpenAPI, we could have the generator flatten that allOf level when it only contains a single child schema, and only use the description from the all of, resulting in being able to add a comment on a property that references a reusable type.

The main question here is:
1. Should it be default behavior?
2. Should it be possible to opt-out of this shortcut?
3. Should it be opt-in only?
