### ISSUE TITLE
JSON content type with a binary schema fails to compile

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#321]
This fails to compile.

```yaml
            application/json:
              schema:
                type: string
                format: binary
```
