### ISSUE TITLE
Empty string enum value breaks the generator

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#33]
We've seen a string enum definition like:

```yaml
type: string
enum:
  - ""
  - foo
  - bar
```

Note the empty string as the first case.

Currently, the generator breaks on it, but we should be able to handle it. Somewhat related to #21.
