### ISSUE TITLE
Support object schemas in query items

### ISSUE THREAD

**Issue by czechboy0** [apple/swift-openapi-generator#35]
We should support encoding non-primitive values as query items, which is prescribed by OpenAPI.

```yaml
        - name: fields
          in: query
          description: Pairs of field=value to filter results
          required: true
          schema:
            type: object
            additionalProperties:
              type: string
```

The above example also uses `additionalProperties`, but _I think_ that shouldn't change the story around serializing object structs into query items.

Somewhat related to #18.

This issue was also encountered in #83.

**Comment by sliemeobn** [comment]
since the docs suggest that "in: query + style: form + exploded: true" is supported I stumbled over this when writing a new server ([slack thread](https://swift-open-source.slack.com/archives/C05AZ55J75K/p1690371613314249?thread_ts=1690370207.963299&cid=C05AZ55J75K))

I was going by this example from the [swagger docs](https://swagger.io/docs/specification/describing-parameters/#query-parameters): 
```
Objects can be serialized as:
form – /points?color=R,100,G,200,B,150 or /points?R=100&G=200&B=150, depending on the explode keyword
```

my desired route would look like this:
```
  /users:
    get:
      operationId: getUsers
      parameters:
      - name: filter
        in: query
        schema:
          type: object
          properties:
            name: { type: string }
            group: { type: string }
            role: { type: string }
        explode: true
        style: form
```

however, the generated code produces an error around the conversion:
```
error: instance method 'setQueryItemAsText(in:name:value:)' requires that 'Operations.getUsers.Input.Query.filterPayload' conform to '_StringConvertible'
                try converter.setQueryItemAsText(
```

in the generated deserializer code (UniversalServer extension)
```swift
    func getUsers(request: Request, metadata: ServerRequestMetadata) async throws -> Response {
        try await handle(
            request: request,
            with: metadata,
            forOperation: Operations.getUsers.id,
            using: APIHandler.getUsers,
            deserializer: { request, metadata in let path: Operations.getUsers.Input.Path = .init()
                let query: Operations.getUsers.Input.Query = .init(
                    filter: try converter.getOptionalQueryItemAsText(
                        in: metadata.queryParameters,
                        name: "filter",
                        as: Operations.getUsers.Input.Query.filterPayload.self
                    )
                )
```

in addition of this being a really useful feature, it feels to me that the docs are incorrectly suggesting that this is supported.
