### ISSUE TITLE
Add configuration option for key encoding/decoding styles

### ISSUE THREAD

**Issue by kelvinlauKL** [apple/swift-openapi-generator#372]
Backend APIs generally use `lower_snake_case`, but Swift developers are accustomed to `lowerCamelCase`. 

Is it possible to configure the encoder/decoders to write idiomatic Swift code? For example, a `POST` request might require a few properties:

```
{
  "some_field_name": <string>
}
```

but I want my generated Swift model to use `lowerCamelCase`:

```
// in openapi.yaml

ResponseBody:
  type: object
  properties: 
    someFieldName: // using lowerCamelCase rather than lower_snake_case
      type: string
```
