### ISSUE TITLE
Generated enums and operations contain character names

### ISSUE THREAD

**Issue by erikhric** [apple/swift-openapi-generator#424]
When I update from 0.1.0 to 1.0.0.alpha.1 my enum value that used to be `basic_image` is now `basic_hyphen_image` string value from backend is `basic_image` <br>
for schema:<br>
```
          type: string
          nullable: false
          enum:
            - basic-video
            - basic-image
```

It also applies to `Operations`:
`get_feed__session_` -> `get_sol_feed_sol__lcub_session_rcub_`
for schema:<br>
```
/feed/{session}:
    get:
      tags:
        - Feed
      summary: Retrieve feed entries for the session
```
