### ISSUE TITLE
Inferred properties aren't detected in 3.0.3 documents

### ISSUE THREAD

**Issue by MahdiBM** [apple/swift-openapi-generator#437]
```yml
components:
  schemas:
    MyType:
      type: object
      properties:
        someName:
          type: string
      required:
        - anotherName /// <--- non-existent required field
```
The generator generates both `someName` and `anotherName` fields. The `anotherName` field will be of type `OpenAPIRuntime.OpenAPIValueContainer`. `someName` will be of the correct type.

OpenAPI should either error or ignore such stuff in the `required` values.
