### ISSUE TITLE
Support schemas.type: string, format: uri generates URL property not String

### ISSUE THREAD

**Issue by zunda-pixel** [apple/swift-openapi-generator#560]
### Motivation

Macro generates `String` property from this `openapi.yaml`
Please change to `URL` property

```yaml
components:
  schemas:
    Sample:
      name: link
      type: string
      format: uri
```

```swift
struct Sample {
  var link: String
}
```  

### Proposed solution

```swift
struct Sample {
  var link: URL
}
```
