### ISSUE TITLE
Different Return Types Depending on the Request Made to the /chat/completions Endpoint in the OpenAI OpenAPI

### ISSUE THREAD

**Issue by paulhdk** [apple/swift-openapi-generator#614]
### Question

I’ve been using the swift-openapi-generator package to generate code for invoking the OpenAI OpenAPI, which is defined [here on GitHub](https://github.com/openai/openai-openapi/blob/master/openapi.yaml).

When invoking the `/chat/completions` endpoint via `createChatCompletion()`, you will receive a `CreateChatCompletionResponse` unless you specified `stream: true` in your request, in that case, you’ll receive several `CreateChatCompletionStreamResponse` objects as the response is being streamed.

This made explicit in the `/chat/completion` definition in OpenAI’s `openapi.yml`:

```
            x-oaiMeta:
                name: Create chat completion
                group: chat
                returns: |
                    Returns a [chat completion](/docs/api-reference/chat/object) object, or a streamed sequence of [chat completion chunk](/docs/api-reference/chat/streaming) objects if the request is streamed.
```

AFAICT, the `CreateChatCompletionStreamResponse` is never linked to the `createChatCompletion()` function in the spec, which is why, I believe, swift-openapi-generator doesn’t have a chance of generating a `createChatCompletion()` implementation that returns streamed responses, and which is why, I’m only seeing a `createChatCompletion()`in my generated `client.swift`file that returns a `ChatCompletionResponse`, indepenet of whether`stream` was set or not.

Is this reasoning correct? Do you have any pointers, or am I missing something?
