### ISSUE TITLE
How to avoid character escaping in strings

### ISSUE THREAD

**Issue by paulhdk** [apple/swift-openapi-generator#621]
### Question

Hi!

I'm generating code with the [OpenAI OpenAPI specification](https://github.com/openai/openai-openapi) and am running into the following issue: the API allows you to pass a base64 image to the `chat/completions` endpoint in the `image_url` field of a `ChatCompletionRequestMessageContentPartImage` object.

```yaml
        ChatCompletionRequestMessageContentPartImage:
            type: object
            title: Image content part
            properties:
                type:
                    type: string
                    enum: ["image_url"]
                    description: The type of the content part.
                image_url:
                    type: object
                    properties:
                        url:
                            type: string
                            description: Either a URL of the image or the base64 encoded image data.
                            format: uri
                        detail:
                            type: string
                            description: Specifies the detail level of the image. Learn more in the [Vision guide](/docs/guides/vision/low-or-high-fidelity-image-understanding).
                            enum: ["auto", "low", "high"]
                            default: "auto"
                    required:
                        - url
            required:
                - type
                - image_url
```

The base64 image string will look like the following: `data:image/jpeg;base64,<base64image>`.

The problem is that I'm getting a string in the final JSON where slashes, which can appear as part of a base64 string, are escaped, which causes my API calls to fail. At least I believe that is the reason why they do.

I tried changing the string format to `format: byte`, but not luck.

Theoretically, one would just somehow have to set the corresponding flag in the JSON encoder. The problem is that even if that were possible, I wouldn't want to disable character escaping globally but only for the specific field.

Does this make sense? Am I missing somethign? Do you have any suggestions?
