### ISSUE TITLE
Generator with the swift-openapi-lambda

### ISSUE THREAD

**Issue by alteredtech** [apple/swift-openapi-generator#726]
### Question

This is probably out of scope of this, but figured I might ask even if it points me in the right direction. I have asked on the `swift-openapi-lambda` but havent heard back on a question I posted 2 months ago.

I am investigating the usage of openapi with lambda. So far it works well with the petstore toy problem however, as the way I understand how the openapi generator and the lambda transport is everything is in a single package. This prevents the ability of writing separate function resources in a sam template.

With this generator, is there a way to have the server code be generated without having to define it in each separate executable? The only method I could think would be having separate openapi specs for each function in the lambda. That would defeat the purpose of the spec in my opinion, breaking apart or combining of separate files.

**Comment by alteredtech** [comment]
I found I could something like this in the package. However, it requires each target conform all the functions of the spec.

```
.executableTarget(
          name: "GetPetsByStatus",
          dependencies: [
            .product(name: "AWSLambdaRuntime", package: "swift-aws-lambda-runtime"),
            .product(name: "AWSLambdaEvents", package: "swift-aws-lambda-events"),
            .product(name: "OpenAPIRuntime",package: "swift-openapi-runtime"),
            .product(name: "OpenAPILambda",package: "swift-openapi-lambda"),
          ],
          path: "Sources/Pet/GetPetsByStatus",
          resources: [
            .copy("../../openapi.yaml"),
            .copy("../../openapi-generator-config.yaml")
          ],
          plugins: [
            .plugin(
                name: "OpenAPIGenerator",
                package: "swift-openapi-generator"
            )
          ]
        ),
```

**Comment by alteredtech** [comment]
I am attempted to get something like this

Current
```
Resources:
  # Lambda function
  PetStore:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        # pass through all HTTP verbs and paths
        Api:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
```

Desired
```
Resources:
  GetPetbyId:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: <Whatever this would be>
      Events:
        Api:
          Type: HttpApi
          Properties:
            Method: get
            Path: /pet/{petId}
  GetPetsbyTags:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: <Whatever this would be>
      Events:
        Api:
          Type: HttpApi
          Properties:
            Method: get
            Path: /pet/findbytags
  GetPetsbyStatus:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: <Whatever this would be>
      Events:
        Api:
          Type: HttpApi
          Properties:
            Method: get
            Path: /pet/findbyStatus
```
